server:
  port: 8080
spring:
  application:
    name: user-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8080/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"